<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>Toolbox.Tools.FunctionGenerator</RootNamespace>
    <ApplicationIcon>app.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Toolbox.Ui.WinForms\Toolbox.Ui.WinForms.csproj" />
    <ProjectReference Include="..\..\Toolbox.Core\Toolbox.Core.csproj" />
  </ItemGroup>

</Project>
